	[package]
	name = "ainalyzer"
	version = "0.1.0"
	authors = ["arttaaz"]
	edition = "2018"

	# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

	[dependencies]
	log = "0.4"
	pretty_env_logger = "0.4"
	druid = { git = "https://github.com/linebender/druid.git" }
