	[package]
	name = "ainalyzer"
	version = "0.1.0"
	authors = ["arttaaz"]
	edition = "2018"

	# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

	[dependencies]
	log = "0.4"
	scrub_log = "0.1.1"
	druid = { git = "https://github.com/linebender/druid.git", rev = "0ca252f28993fe5394bc4dc96ab6f8253242477b" }
	libgtp = { git = "https://github.com/arttaaz/libgtp.git" }
	sgf-parser = "2.4"
